$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1441792321971.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f4f44182f41048e6ba0c435808a680b3",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a51f95e5b7ba4e3fa3e3930da214fcfe",
          "label":"1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a07a9439d0b049908d3fb66259dec2cc",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"466a647b009341e69a5f69f9cbd03c57",
                  "label":"",
                  "parentDynamicPanel":"a51f95e5b7ba4e3fa3e3930da214fcfe",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "size":{
                      "width":150,
                      "height":180},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"228ffe906e8b49b2b0dfe2c31f034701",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a51f95e5b7ba4e3fa3e3930da214fcfe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "size":{
                          "width":150,
                          "height":180},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 1 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["a51f95e5b7ba4e3fa3e3930da214fcfe"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"e14cfedd7ce54f93a8eb3b2358d99436",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5000134b6b6f4259a30cc084efd51c68",
                  "label":"",
                  "parentDynamicPanel":"a51f95e5b7ba4e3fa3e3930da214fcfe",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "size":{
                      "width":150,
                      "height":180},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa4ffcd8b4c644a4b694234b8f91caf4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a51f95e5b7ba4e3fa3e3930da214fcfe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "size":{
                          "width":150,
                          "height":180},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 1 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["a51f95e5b7ba4e3fa3e3930da214fcfe"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"755c09464141434d80a9b6087ac9524e",
          "label":"2",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2bb5cfb78a9048d4b5dea77f9200f4d1",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"53c9a0383c98436d87c6b4fe5fb1176c",
                  "label":"",
                  "parentDynamicPanel":"755c09464141434d80a9b6087ac9524e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "size":{
                      "width":150,
                      "height":180},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13bcb9dbf60f4ce38315ebabe27c8ebb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"755c09464141434d80a9b6087ac9524e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "size":{
                          "width":150,
                          "height":180},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 2 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["755c09464141434d80a9b6087ac9524e"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u6.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"75e148e71fc24890808e65007a74bcec",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"65d45b09fbc94dfca1b7ffdcbc7bf739",
                  "label":"",
                  "parentDynamicPanel":"755c09464141434d80a9b6087ac9524e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "size":{
                      "width":150,
                      "height":180},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec0ee92052524d72b695c9aca64b2ffc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"755c09464141434d80a9b6087ac9524e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "size":{
                          "width":150,
                          "height":180},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 2 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["755c09464141434d80a9b6087ac9524e"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u8.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"470bcae957904ac0a8586a4d7f05edbd",
          "label":"3",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"36a0eba75e264901bd5a5d662aa60726",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"23eb32133b214df188ea626da7320092",
                  "label":"",
                  "parentDynamicPanel":"470bcae957904ac0a8586a4d7f05edbd",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "size":{
                      "width":150,
                      "height":180},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3faa4121ffc74d6996b2ed41a8d87485",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"470bcae957904ac0a8586a4d7f05edbd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "size":{
                          "width":150,
                          "height":180},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 3 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["470bcae957904ac0a8586a4d7f05edbd"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u11.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"e42d029ed26b4e29bc7e80d06cbbbdee",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c8ec8ee6b9dc409091ef17b91845384a",
                  "label":"",
                  "parentDynamicPanel":"470bcae957904ac0a8586a4d7f05edbd",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "size":{
                      "width":150,
                      "height":180},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"418eff7e255a4c69ba9b23a02544da02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"470bcae957904ac0a8586a4d7f05edbd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "size":{
                          "width":150,
                          "height":180},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 3 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["470bcae957904ac0a8586a4d7f05edbd"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u13.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"cce658ca77474a439d0cd70920c557c3",
          "label":"4",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0d3839ef578b4f638f8576c3db27248b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dbe141ae45264fd59e4f35d241a50a92",
                  "label":"",
                  "parentDynamicPanel":"cce658ca77474a439d0cd70920c557c3",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "size":{
                      "width":150,
                      "height":180},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0dac75bf4ecb461a95d433efba741404",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cce658ca77474a439d0cd70920c557c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "size":{
                          "width":150,
                          "height":180},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 4 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["cce658ca77474a439d0cd70920c557c3"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u16.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"63b3957b407f4bd29d7ccdc96d20636f",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ecb9173e49d34405b25e289541ae9fa0",
                  "label":"",
                  "parentDynamicPanel":"cce658ca77474a439d0cd70920c557c3",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "size":{
                      "width":150,
                      "height":180},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"441780f1de1945e9b925c07afabb0342",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cce658ca77474a439d0cd70920c557c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "size":{
                          "width":150,
                          "height":180},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 4 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["cce658ca77474a439d0cd70920c557c3"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u18.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "a51f95e5b7ba4e3fa3e3930da214fcfe":{
      "scriptId":"u0"},
    "466a647b009341e69a5f69f9cbd03c57":{
      "scriptId":"u1"},
    "228ffe906e8b49b2b0dfe2c31f034701":{
      "scriptId":"u2"},
    "5000134b6b6f4259a30cc084efd51c68":{
      "scriptId":"u3"},
    "aa4ffcd8b4c644a4b694234b8f91caf4":{
      "scriptId":"u4"},
    "755c09464141434d80a9b6087ac9524e":{
      "scriptId":"u5"},
    "53c9a0383c98436d87c6b4fe5fb1176c":{
      "scriptId":"u6"},
    "13bcb9dbf60f4ce38315ebabe27c8ebb":{
      "scriptId":"u7"},
    "65d45b09fbc94dfca1b7ffdcbc7bf739":{
      "scriptId":"u8"},
    "ec0ee92052524d72b695c9aca64b2ffc":{
      "scriptId":"u9"},
    "470bcae957904ac0a8586a4d7f05edbd":{
      "scriptId":"u10"},
    "23eb32133b214df188ea626da7320092":{
      "scriptId":"u11"},
    "3faa4121ffc74d6996b2ed41a8d87485":{
      "scriptId":"u12"},
    "c8ec8ee6b9dc409091ef17b91845384a":{
      "scriptId":"u13"},
    "418eff7e255a4c69ba9b23a02544da02":{
      "scriptId":"u14"},
    "cce658ca77474a439d0cd70920c557c3":{
      "scriptId":"u15"},
    "dbe141ae45264fd59e4f35d241a50a92":{
      "scriptId":"u16"},
    "0dac75bf4ecb461a95d433efba741404":{
      "scriptId":"u17"},
    "ecb9173e49d34405b25e289541ae9fa0":{
      "scriptId":"u18"},
    "441780f1de1945e9b925c07afabb0342":{
      "scriptId":"u19"}}});